<?php

declare(strict_types=1);

namespace Lemonade\Framework\Discovery\Robots;

use Lemonade\Framework\Clock\ClockInterface;
use Lemonade\Framework\Core\Config;
use Lemonade\Framework\Support\BaseUrlResolver;

final class RobotsTxtGenerator
{
    public function __construct(
        private readonly Config $config,
        private readonly BaseUrlResolver $baseUrlResolver,
        private readonly ClockInterface $clock,
    ) {}

    public function generate(): string
    {
        $rules = $this->config->array('discovery.robots.rules');
        $lines = [];
        $this->appendHeader($lines);

        foreach ($rules as $agent => $rule) {
            if (!is_string($agent) || !is_array($rule)) {
                continue;
            }

            $lines[] = 'User-agent: ' . $agent;
            $allowList = $rule['allow'] ?? [];
            if (is_array($allowList)) {
                foreach ($allowList as $allow) {
                    if (is_string($allow) && trim($allow) !== '') {
                        $lines[] = 'Allow: ' . $allow;
                    }
                }
            }
            $disallowList = $rule['disallow'] ?? [];
            if (is_array($disallowList)) {
                foreach ($disallowList as $disallow) {
                    if (is_string($disallow) && trim($disallow) !== '') {
                        $lines[] = 'Disallow: ' . $disallow;
                    }
                }
            }
            $lines[] = '';
        }

        foreach ($this->config->array('discovery.robots.sitemaps') as $sitemap) {
            if (!is_string($sitemap) || trim($sitemap) === '') {
                continue;
            }
            $lines[] = 'Sitemap: ' . $this->normalizeSitemapUrl($sitemap);
        }

        return trim(implode("\n", $lines)) . "\n";
    }

    /**
     * @param list<string> $lines
     */
    private function appendHeader(array &$lines): void
    {
        $enabled = $this->config->bool('discovery.robots.header.enabled', true);
        if (!$enabled) {
            return;
        }

        $generator = $this->config->string('discovery.robots.header.generator', 'Lemonade Framework') ?? 'Lemonade Framework';
        $dateFormat = $this->config->string('discovery.robots.header.date_format', 'Y-m-d H:i:s') ?? 'Y-m-d H:i:s';
        $baseUrl = rtrim($this->baseUrlResolver->baseUrl(), '/');

        $safeGenerator = $this->sanitizeSingleLine($generator);
        $safeBaseUrl = $this->sanitizeSingleLine($baseUrl);
        $generatedAt = $this->clock->now()->format($dateFormat);

        $lines[] = '# robots.txt for ' . $safeBaseUrl;
        $lines[] = '# Generated by ' . $safeGenerator . ' on ' . $generatedAt;
        $lines[] = '';
    }

    private function normalizeSitemapUrl(string $url): string
    {
        if (str_starts_with($url, 'http://') || str_starts_with($url, 'https://')) {
            return $url;
        }

        return $this->baseUrlResolver->baseUrl($url);
    }

    private function sanitizeSingleLine(string $value): string
    {
        $line = str_replace(["\r", "\n"], ' ', $value);

        return trim(preg_replace('/\s+/', ' ', $line) ?? '');
    }
}
