<?php

declare(strict_types=1);

namespace Lemonade\Framework\Discovery\Robots;

use Lemonade\Framework\Clock\ClockInterface;
use Lemonade\Framework\Discovery\Config\RobotsConfig;
use Lemonade\Framework\Discovery\Config\RobotsRuleConfig;
use Lemonade\Framework\Support\BaseUrlResolver;

final class RobotsTxtGenerator
{
    public function __construct(
        private readonly RobotsConfig $config,
        private readonly BaseUrlResolver $baseUrlResolver,
        private readonly ClockInterface $clock,
    ) {}

    public function generate(): string
    {
        $lines = [];
        $this->appendHeader($lines);

        foreach ($this->config->rules as $rule) {
            $this->appendRuleLines($lines, $rule);
            $lines[] = '';
        }

        foreach ($this->config->sitemaps as $sitemap) {
            $lines[] = 'Sitemap: ' . $this->normalizeSitemapUrl($sitemap);
        }

        return trim(implode("\n", $lines)) . "\n";
    }

    /**
     * @param list<string> $lines
     */
    private function appendHeader(array &$lines): void
    {
        if (!$this->config->header->enabled) {
            return;
        }

        $baseUrl = rtrim($this->baseUrlResolver->baseUrl(), '/');

        $safeGenerator = $this->sanitizeSingleLine($this->config->header->generator);
        $safeBaseUrl = $this->sanitizeSingleLine($baseUrl);
        $generatedAt = $this->clock->now()->format($this->config->header->dateFormat);

        $lines[] = '# robots.txt for ' . $safeBaseUrl;
        $lines[] = '# Generated by ' . $safeGenerator . ' on ' . $generatedAt;
        $lines[] = '';
    }

    /**
     * @param list<string> $lines
     */
    private function appendRuleLines(array &$lines, RobotsRuleConfig $rule): void
    {
        $lines[] = 'User-agent: ' . $rule->agent;

        foreach ($rule->allow as $allow) {
            $lines[] = 'Allow: ' . $allow;
        }

        foreach ($rule->disallow as $disallow) {
            $lines[] = 'Disallow: ' . $disallow;
        }
    }

    private function normalizeSitemapUrl(string $url): string
    {
        if (str_starts_with($url, 'http://') || str_starts_with($url, 'https://')) {
            return $url;
        }

        return $this->baseUrlResolver->baseUrl($url);
    }

    private function sanitizeSingleLine(string $value): string
    {
        $line = str_replace(["\r", "\n"], ' ', $value);

        return trim(preg_replace('/\s+/', ' ', $line) ?? '');
    }
}
