<?php

declare(strict_types=1);

namespace Lemonade\Framework\Tests\Unit\Discovery;

use DateTimeImmutable;
use Lemonade\Framework\Clock\ClockInterface;
use Lemonade\Framework\Core\Config\AppConfig;
use Lemonade\Framework\Discovery\Config\RobotsConfig;
use Lemonade\Framework\Discovery\Config\RobotsHeaderConfig;
use Lemonade\Framework\Discovery\Config\RobotsRuleConfig;
use Lemonade\Framework\Discovery\Robots\RobotsTxtGenerator;
use Lemonade\Framework\Support\BaseUrlResolver;
use PHPUnit\Framework\TestCase;

final class RobotsTxtGeneratorTest extends TestCase
{
    public function testGeneratesRulesAndAbsoluteSitemap(): void
    {
        $baseUrl = 'https://example.com';
        $config = new RobotsConfig(
            enabled: true,
            route: '/robots.txt',
            header: new RobotsHeaderConfig(true, 'Lemonade Framework', 'Y-m-d H:i:s'),
            rules: [
                new RobotsRuleConfig('*', ['/'], ['/admin', '/login']),
                new RobotsRuleConfig('Googlebot', ['/docs'], []),
            ],
            sitemaps: ['/sitemap.xml'],
        );

        $txt = (new RobotsTxtGenerator(
            $config,
            new BaseUrlResolver(new AppConfig(null, $baseUrl, '', '', 'testing', false, '', '', '')),
            new FixedClock(new DateTimeImmutable('2026-05-29 14:16:39')),
        ))->generate();

        self::assertStringContainsString("# robots.txt for https://example.com\n", $txt);
        self::assertStringContainsString("# Generated by Lemonade Framework on 2026-05-29 14:16:39\n", $txt);
        self::assertStringContainsString("User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /login", $txt);
        self::assertStringContainsString("User-agent: Googlebot\nAllow: /docs", $txt);
        self::assertStringContainsString('Sitemap: https://example.com/sitemap.xml', $txt);
    }

    public function testHeaderCanBeDisabled(): void
    {
        $baseUrl = 'https://example.com';
        $config = new RobotsConfig(
            enabled: true,
            route: '/robots.txt',
            header: new RobotsHeaderConfig(false, 'Lemonade Framework', 'Y-m-d H:i:s'),
            rules: [
                new RobotsRuleConfig('*', ['/'], ['/admin']),
            ],
            sitemaps: ['/sitemap.xml'],
        );

        $txt = (new RobotsTxtGenerator(
            $config,
            new BaseUrlResolver(new AppConfig(null, $baseUrl, '', '', 'testing', false, '', '', '')),
            new FixedClock(new DateTimeImmutable('2026-05-29 14:16:39')),
        ))->generate();

        self::assertStringStartsWith("User-agent: *\n", $txt);
        self::assertStringNotContainsString('# robots.txt for', $txt);
        self::assertStringNotContainsString('# Generated by', $txt);
    }
}

final class FixedClock implements ClockInterface
{
    public function __construct(
        private readonly DateTimeImmutable $now,
    ) {}

    public function now(): DateTimeImmutable
    {
        return $this->now;
    }
}
