<?php

declare(strict_types=1);

namespace Lemonade\Framework\Tests\Unit\Discovery;

use DateTimeImmutable;
use Lemonade\Framework\Clock\ClockInterface;
use Lemonade\Framework\Core\Config;
use Lemonade\Framework\Discovery\Robots\RobotsTxtGenerator;
use Lemonade\Framework\Support\BaseUrlResolver;
use PHPUnit\Framework\TestCase;

final class RobotsTxtGeneratorTest extends TestCase
{
    public function testGeneratesRulesAndAbsoluteSitemap(): void
    {
        $config = new Config([
            'app' => ['base_url' => 'https://example.com'],
            'discovery' => [
                'robots' => [
                    'header' => [
                        'enabled' => true,
                        'generator' => 'Lemonade Framework',
                        'date_format' => 'Y-m-d H:i:s',
                    ],
                    'rules' => [
                        '*' => [
                            'allow' => ['/'],
                            'disallow' => ['/admin', '/login'],
                        ],
                        'Googlebot' => [
                            'allow' => ['/docs'],
                            'disallow' => [],
                        ],
                    ],
                    'sitemaps' => ['/sitemap.xml'],
                ],
            ],
        ]);

        $txt = (new RobotsTxtGenerator(
            $config,
            new BaseUrlResolver($config),
            new FixedClock(new DateTimeImmutable('2026-05-29 14:16:39')),
        ))->generate();

        self::assertStringContainsString("# robots.txt for https://example.com\n", $txt);
        self::assertStringContainsString("# Generated by Lemonade Framework on 2026-05-29 14:16:39\n", $txt);
        self::assertStringContainsString("User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /login", $txt);
        self::assertStringContainsString("User-agent: Googlebot\nAllow: /docs", $txt);
        self::assertStringContainsString('Sitemap: https://example.com/sitemap.xml', $txt);
    }

    public function testHeaderCanBeDisabled(): void
    {
        $config = new Config([
            'app' => ['base_url' => 'https://example.com'],
            'discovery' => [
                'robots' => [
                    'header' => [
                        'enabled' => false,
                    ],
                    'rules' => [
                        '*' => [
                            'allow' => ['/'],
                            'disallow' => ['/admin'],
                        ],
                    ],
                    'sitemaps' => ['/sitemap.xml'],
                ],
            ],
        ]);

        $txt = (new RobotsTxtGenerator(
            $config,
            new BaseUrlResolver($config),
            new FixedClock(new DateTimeImmutable('2026-05-29 14:16:39')),
        ))->generate();

        self::assertStringStartsWith("User-agent: *\n", $txt);
        self::assertStringNotContainsString('# robots.txt for', $txt);
        self::assertStringNotContainsString('# Generated by', $txt);
    }
}

final class FixedClock implements ClockInterface
{
    public function __construct(
        private readonly DateTimeImmutable $now,
    ) {}

    public function now(): DateTimeImmutable
    {
        return $this->now;
    }
}
