<?php

declare(strict_types=1);

namespace Lemonade\Framework\Tests\Unit\Discovery;

use Lemonade\Framework\Container\Container;
use Lemonade\Framework\Core\Config\AppConfig;
use Lemonade\Framework\Discovery\Config\SitemapConfig;
use Lemonade\Framework\Discovery\Config\SitemapRouteConfig;
use Lemonade\Framework\Discovery\Sitemap\RouteSitemapProvider;
use Lemonade\Framework\Discovery\Sitemap\SitemapFile;
use Lemonade\Framework\Discovery\Sitemap\SitemapGenerator;
use Lemonade\Framework\Discovery\Sitemap\SitemapIndexGenerator;
use Lemonade\Framework\Discovery\Sitemap\SitemapProviderRegistry;
use Lemonade\Framework\Routing\Router;
use Lemonade\Framework\Routing\UrlGenerator;
use Lemonade\Framework\Support\BaseUrlResolver;
use PHPUnit\Framework\TestCase;

final class SitemapGeneratorsTest extends TestCase
{
    public function testSitemapGeneratorWritesUrlsetUsingXmlStreamWriter(): void
    {
        $router = new Router();
        $router->getNamed('home', '/', 'HomeController@index');
        $baseUrl = 'https://example.com';
        $config = $this->sitemapConfig(routes: [new SitemapRouteConfig('home', [], null, null, null)]);
        $registry = new SitemapProviderRegistry(new Container(), $config, new RouteSitemapProvider($config, new UrlGenerator($router)));
        $generator = new SitemapGenerator(
            $registry,
            new BaseUrlResolver(new AppConfig(null, $baseUrl, '', '', 'testing', false, '', '', '')),
            $config,
        );

        $stream = fopen('php://temp', 'w+b');
        self::assertIsResource($stream);
        $generator->writeUrlset($stream, $generator->urls());
        rewind($stream);
        $xml = stream_get_contents($stream);
        fclose($stream);

        self::assertIsString($xml);
        self::assertStringContainsString('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">', $xml);
        self::assertStringContainsString('<loc>https://example.com/</loc>', $xml);
        self::assertStringNotContainsString('# Generated by', $xml);
    }

    public function testSitemapIndexGeneratorWritesSitemapindex(): void
    {
        $stream = fopen('php://temp', 'w+b');
        self::assertIsResource($stream);

        $index = new SitemapIndexGenerator();
        $index->writeIndex($stream, [new SitemapFile('/tmp/a.xml', 'https://example.com/sitemap-1.xml', '2026-05-29')]);
        rewind($stream);
        $xml = stream_get_contents($stream);
        fclose($stream);

        self::assertIsString($xml);
        self::assertStringContainsString('<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">', $xml);
        self::assertStringContainsString('<loc>https://example.com/sitemap-1.xml</loc>', $xml);
    }

    /**
     * @param list<SitemapRouteConfig> $routes
     */
    private function sitemapConfig(array $routes = []): SitemapConfig
    {
        return new SitemapConfig(
            enabled: false,
            route: '/sitemap.xml',
            cliOutput: true,
            mode: 'stream',
            baseUrl: null,
            routes: $routes,
            providers: [],
            cachePath: 'storage/cache/discovery',
            filename: 'sitemap.xml',
            indexFilename: 'sitemap.xml',
            gzip: false,
            maxUrlsPerFile: 50000,
            maxUncompressedBytes: 52428800,
            deduplicate: false,
            onInvalidUrl: 'fail',
        );
    }
}
